import { Shoe_1, Shoe_2, Shoe_3, Shoe_4, Shoe_5 } from "../assets/image.js";

const products = [
  {
    id: 1,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_1,
    name: "Nike Air Max 270",
    discountPrice: 2224,
    price: 34303,
    ratingValue: 2.5,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 2,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_2,
    name: "Nike Air Max 270",
    discountPrice: 2024,
    price: 34303,
    ratingValue: 2,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 3,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_3,
    name: "Nike Air Max 270",
    discountPrice: 2024,
    price: 34303,
    ratingValue: 2,
    discountPercent: 30,
    brand: "Airmax",
    isBrand: true,
  },
  {
    id: 4,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_4,
    name: "Nike Air Max 270",
    discountPrice: 2924,
    price: 34303,
    ratingValue: 4.5,
    discountPercent: 30,
    brand: "Adidas",
    isBrand: true,
  },
  {
    id: 5,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2334,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Airmax",
    isBrand: true,
  },
  {
    id: 6,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2354,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 7,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2384,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Vans",
    isBrand: false,
  },
  {
    id: 8,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2322,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Adidas",
    isBrand: true,
  },
  {
    id: 9,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2222,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 10,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2142,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Adidas",
    isBrand: true,
  },
  {
    id: 11,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 4123,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Air Jordan",
    isBrand: true,
  },
  {
    id: 12,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 5332,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 13,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2342,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 14,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Air Jordan",
    isBrand: true,
  },
  {
    id: 15,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Adidas",
    isBrand: true,
  },
  {
    id: 16,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 17,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Airmax",
    isBrand: true,
  },
  {
    id: 18,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Airmax",
    isBrand: true,
  },
  {
    id: 19,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Air Jordan",
    isBrand: true,
  },
  {
    id: 20,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 21,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Adidas",
    isBrand: true,
  },
  {
    id: 22,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 23,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Vans",
    isBrand: false,
  },
  {
    id: 24,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 25,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 26,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 27,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 28,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Nike",
    isBrand: true,
  },
  {
    id: 29,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Airmax",
    isBrand: true,
  },
  {
    id: 30,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Adidas",
    isBrand: true,
  },
  {
    id: 31,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 32,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Airmax",
    isBrand: true,
  },
  {
    id: 33,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Air Jordan",
    isBrand: true,
  },
  {
    id: 34,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 35,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 36,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2014,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 37,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Red Tape",
    isBrand: true,
  },
  {
    id: 38,
    isHot: true,
    hotDeal: false,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 39,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 1054,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Air Jordan",
    isBrand: true,
  },
  {
    id: 40,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 1548,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 41,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 1057,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 42,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 1115,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 43,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2005,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 44,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2344,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 45,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
  {
    id: 46,
    isHot: true,
    hotDeal: true,
    imageUrl: Shoe_5,
    name: "Nike Air Max 270",
    discountPrice: 2324,
    price: 34303,
    ratingValue: 3,
    discountPercent: 30,
    brand: "Reebok",
    isBrand: true,
  },
];

export { products };
